### PR TITLE
add dynamic command aliases

### PR DESCRIPTION
**Pull request by Felk**
Partially fixes https://github.com/TwitchPlaysPokemon/tpp-core/issues/401

no hard-coded arguments as-is

### CODE REVIEW

**Comment by Felk** [comment]
Now it also has hard-coded arguments:

```
>>> !aliases add felk badges @felkcraft
Command alias 'felk' now redirects to: badges @felkcraft
>>> !aliases list
These command aliases currently exist: felk -> badges @felkcraft
>>> !felk
FelkCraft has no badges.
>>> !aliases remove felk
Command alias 'felk' was removed.
>>> !aliases list
There currently are no command aliases.
>>> !felk
unknown command 'felk'
```

**Comment by Felk** [comment]
waiting for feedback, but will eventually merge anyway if noone objects

**Comment by m4-used-rollout** [comment]
Does it also append any parameters given to the aliased command?
> For instance, we could have a !bestbadges command that would map to !dex complement-from-dupes so a user could say !bestbadges m4_used_rollout to execute !dex complement-from-dupes m4_used_rollout

**Comment by Felk** [comment]
Yes!

**Comment by m4-used-rollout** [comment]
Can it be used to trigger commands in old core?

**Comment by Felk** [comment]
Oh, hmm... Probably not but I don't know, haven't actually tried that

**Comment by Felk** [comment]
It doesn't work right now, and it is surprisingly complicated. How important is that?

**Comment by Felk** [comment]
89ee4819c3376ad6451265619cc21463262f6363 looks like it does the job, even if it's quite hacky. Does that look good so far?

**Comment by m4-used-rollout** [comment]
If it works it’s fine with me

**Pull request merged**
