### PR TITLE
Fix #112

### LINKED ISSUE #112: !badges command is not agnostic to the argument order
The !badges command should work with both `!badges <user> <species>` and `!badges <species> <user>`.  
However, `!badges pidgey felkcraft` works, but `!badges felkcraft pidgey` gives the following error:

> No pokemon with the name 'felkcraft' was recognized. Please supply a valid name, or prefix with '#' to supply and pokedex number instead

### PR DESCRIPTION
**Pull request by 6100m**
It was actually easier than I expected. I hope to do more PR's of more complex stuff as I gain more skill.
EDIT: Sorry if I referenced 2, that was a accident.

### CODE REVIEW

**Comment by aaaaaa123456789** [comment]
Doesn't even build.

**Comment by 6100m** [comment]
@aaaaaa123456789 Yeah I know, something happened when I swapped it around.
Optional<User>, <ParseArgsOptional<PkmnSpecies>>

Maybe this is the way it wants it?

**Comment by aaaaaa123456789** [comment]
Please test your code locally instead of flooding us with commits that don't even compile, let alone build.

**Comment by 6100m** [comment]
I don't have a method to test it actually, yeah apologizes for so many commits.

**Comment by aaaaaa123456789** [comment]
In that case, given that you're clueless about the syntax of the language, I'm going to prevent our inboxes from getting flooded.

**Comment by 6100m** [comment]
And yeah, this isn't my code to begin with, I am fixing Issue 112. I am trying one thing after another until it compiles.

**Pull request closed without merging**
