### PR TITLE
ArgsParsing.Tests: use NFluent for exception assertions

### PR DESCRIPTION
**Pull request by Felk**
just an experiment to see how you like fluent assertions

### CODE REVIEW

**Comment by red031000** [comment]
what's the advantage to this?

**Comment by Felk** [comment]
> what's the advantage to this?

nothing, just readability, and that's subjective

**Comment by red031000** [comment]
do we want to do this then? maybe @m4-used-rollout has an opinion on which one is better

**Comment by red031000** [comment]
can we either decide if we want this or close it

**Comment by Felk** [comment]
I don't know. I like it, I feel like it's up to you liking it as well as m4 probably won't be involved all that much in new-core C# code

**Comment by red031000** [comment]
honestly I'm a bit unsure on it, I like the format, but I don't like that it's another (unnecessary imo) package, and I also don't particularly like the syntax for .And

**Comment by Felk** [comment]
alright, let's not do it. at least for now

**Pull request closed without merging**
